name: Ruff Lint

on:
  push:
    branches:
      - main
    paths:
      - "nonebot_plugin_dcqq_relay/**"
  pull_request:
    paths:
      - "nonebot_plugin_dcqq_relay/**"

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Ruff Lint
        uses: chartboost/ruff-action@v1
        with:
          src: "./nonebot_plugin_dcqq_relay"
